name: SinCity
main: de.minestar.SinCity.Core
version: 1.0
depend: [FalseBookCore, MinestarCore]
commands:
  ngselect:
    description: Toggle selectionmode
    usage: /ngselect    
  ngregen:
    description: Regenerates the selected chunks
    usage: /ngregen     