name: SinCity
main: de.minestar.SinCity.Core
version: 0.50
depend: [FalseBookCore]
commands:
  ngselect:
    description: Toggle selectionmode
    usage: /ngselect    
  ngregen:
    description: Regenerates the selected chunks
    usage: /ngregen     