name: SinCity
main: de.minestar.SinCity.Core
version: ${pom.version}
depend: [MineStarLibrary, FalseBookCore, MinestarCore]
commands:
  ngselect:
    description: Toggle selectionmode
    usage: /ngselect    
  ngregen:
    description: Regenerates the selected chunks
    usage: /ngregen
  ngpartregen:
    description: Regenerates the selected blocks
    usage: /ngregen
  ngbiome:
    description: Set the biome
    usage: /ngbiome     
  ngaddcorner:
    description: Add a corner
    usage: /ngaddcorner
  ngsavearea:
    description: Save the area
    usage: /ngsavearea
  ngcleararea:
    description: Clear the selection
    usage: /ngcleararea
  ngdeletearea:
    description: Delete the area
    usage: /ngdeletearea    
    